name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - uses: vedhavyas/generate-changelog@v4.0.2
        id: changelog-generator
        with:
          commit-template: '- {hash} → {title}'
          template: |
            ### Changelog

            {commits}

            {range}

            ❤
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: ${{ steps.changelog-generator.outputs.changelog }}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
